### ISSUE TITLE
broken towers on the right side of the field

### ISSUE THREAD

**Issue by Timtam** [Timtam/ggj17#2]
It seems that towers placed on the right side of the field (x-coordinate 13+) aren't usable at all. You can't click onto them directly after they got build and they don't shoot at all, or shoot into the wrong direction (animation) without dealing damage at all.
Example fields (approximated, since counting can be somewhat problematic):
13,8 (the field surrounded by ways in every direction)
14,10

**Comment by 999eagle** [comment]
fixed in caa871ef34f3d47866c7a4e4adcdb24dbe63b50a
