### ISSUE TITLE
code quality is bad

### ISSUE THREAD

**Issue by 999eagle** [Timtam/ggj17#3]
* code should be refactored completely
* spacing and names should be unified

**Comment by 999eagle** [comment]
first steps done in commit 5d81a8fd474e65e08f66642be2984c753daf62da
needs more testing

**Comment by Timtam** [comment]
one more step forward
* sorted all files into folders related to their actual function
* using relative imports instead of absolute ones
again, more testing needed

**Comment by Timtam** [comment]
should be fine for now. reopen or create new issue if some explicit problems occur.
