### ISSUE TITLE
option to disable the splash screen

### ISSUE THREAD

**Issue by Timtam** [Timtam/ggj17#6]
... seriously needed ;)

**Comment by Timtam** [comment]
implemented in newest commit, just someone who will have to add it to the options screen and activate it constantly in main.py

**Comment by Timtam** [comment]
@MrWoodpecker or @999eagle maybe? ;)

**Comment by 999eagle** [comment]
done in commit ad23ed8eecef162acdd8d5b3ad69c43f58077524
